<?php
//ESTAS CONSTANTES SIRVEN PARA LAS VISTAS QUE CONTIENEN HEADER Y FOOTER, SIRVEN PARA SI EN ALGUN MOMENTO CAMBIO DE RUTA LOS ARCHIVOS DEL HEADER Y FOORTER SOLO TENGA QUE CAMBIARL ESTAS CONSTANTES Y NO CADA VISTA QUE IMPLEMENTE ESTAS
const HEADER_TEMPLATE = "./view/includes/header.php";
const FOOTER_TEMPLATE = "./view/includes/footer.php";